brewery/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeBrewery.as_view(), name='home'),
    # path('tank/<int:pk>/', AllTanks.as_view(), name='tanks'),
    path('tank/<int:pk>/', DetailTank.as_view(), name='tanks'),
    path('add-measuring/', CreateMeasuring.as_view(), name='add_measuring'),
    path('add_tank/', AddTanks.as_view(), name='add_tank'),
    path('tank/<int:pk>/delete_tank/', DeleteTank.as_view(), name='delete_tank'),
]

brewery_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brewery.urls'))
]

brewery/models.py
from django.db import models
from django.urls import reverse


class Tank(models.Model):
    """номера цкт"""
    number = models.IntegerField(db_index=True)
    title = models.ForeignKey('Beer', on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.number} - {self.title}'

    def get_absolute_url(self):
        # return reverse('tanks', kwargs={"tank_id": self.pk})
        return 'home/'


class Beer(models.Model):
    """сорт пива"""
    title = models.CharField(max_length=150, db_index=True)

    def __str__(self):
        return self.title


class Measuring(models.Model):
    """необходимые измерения"""
    # title = models.ForeignKey(Beer, on_delete=models.PROTECT)
    temperature = models.FloatField(verbose_name='Температура')
    density = models.FloatField(verbose_name='Плотность')
    data_meas = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=500, blank=True)
    tank = models.ForeignKey(Tank, on_delete=models.CASCADE, verbose_name='Номер')
    pressure = models.FloatField(default=0, blank=True, verbose_name='Давление')
    # def __str__(self):
    #     return f'{self.pk}'

    def get_absolute_url(self):
        # return reverse('tanks', kwargs={"tank_id": self.tank.pk})
        return 'add-measuring/'

brewery/forms.py
from django import forms
from .models import Measuring, Tank


class MeasuringForm(forms.ModelForm):
    class Meta:
        model = Measuring
        fields = ['tank', 'temperature', 'density', 'pressure', 'comment']
        widgets = {
            # 'tank': forms.NumberInput(attrs={'class': 'form-control'}),
            # 'title': forms.TextInput(attrs={'class': 'form-control'}),
            'temperature': forms.NumberInput(attrs={'class': 'form-control'}),
            'density': forms.NumberInput(attrs={'class': 'form-control'}),
            'pressure': forms.NumberInput(attrs={'class': 'form-control'}),
            'comment': forms.TextInput(attrs={'class': 'form-control'}),
        }


class AddTankForm(forms.ModelForm):
    class Meta:
        model = Tank
        fields = ['title', 'number']
        widgets = {
            'number': forms.NumberInput(attrs={'class': 'form-control'}),
        }


# class DeleteTankForm(forms.ModelForm):
#     class Meta:
#         model = Tank
#         fields = ['title', 'number']

brewery/views.py
from django.views.generic import ListView, CreateView, DeleteView, DetailView
from django.urls.base import reverse_lazy, reverse

from .models import Measuring, Tank
from .forms import MeasuringForm, AddTankForm


class HomeBrewery(ListView):
    model = Measuring
    context_object_name = 'brewery'
    template_name = 'brewery/measuring_list.html'


class DetailTank(DetailView):
    model = Tank
    context_object_name = 'brewery'
    template_name = 'brewery/tank_detail.html'

    # def get_queryset(self):
    #     return Tank.objects.filter(id=self.kwargs['pk'])


class AllTanks(ListView):
    model = Measuring
    template_name = 'brewery/measuring_list.html'
    context_object_name = 'brewery'

    def get_queryset(self):
        return Measuring.objects.filter(tank_id=self.kwargs['pk'])


class CreateMeasuring(CreateView):
    form_class = MeasuringForm
    template_name = 'brewery/add_measuring.html'


class AddTanks(CreateView):
    form_class = AddTankForm
    template_name = 'brewery/add_tank.html'
    success_url = reverse_lazy('home')


class DeleteTank(DeleteView):
    model = Tank
    template_name = 'brewery/delete_tank.html'

    success_url = reverse_lazy('home')

brewery/templates/brewery/add_measuring.html
{% extends 'base.html' %}

{% block title %}
Add Measuring :: {{ block.super }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1>Add Measuring</h1>

<form action="{% url 'add_measuring' %}" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">Add Measuring</button>
</form>

{% endblock %}

brewery/templates/brewery/add_tank.html
{% extends 'base.html' %}

{% block title %}
Add Tank :: {{ block.super }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1>Add Tank</h1>

<form action="{% url 'add_tank' %}" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">Add Tank</button>
</form>

{% endblock %}

brewery/templates/brewery/delete_tank.html
{% extends 'base.html' %}

{% block title %}
Add Tank :: {{ block.super }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1>Delete {{ object.number }} Tank?</h1>

 <form method="post">
     {% csrf_token %}
     <p>Are you sure you want to delete?</p>
     <p>This cannot be undone!</p>
     <button type="submit" class="btn btn-danger">Delete</button>
     <a href="{% url 'tanks' object.pk  %}" class="btn btn-info">Beck</a>
 </form>
{% endblock %}

brewery/templates/brewery/measuring_list.html
{% extends 'base.html' %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">t°C</th>
        <th scope="col">p°</th>
        <th scope="col">Date</th>
        <th scope="col">P</th>
        <th scope="col">Comment</th>
    </tr>
    </thead>
    {% for item in brewery %}
    <tbody>
    <tr>
        <th scope="row">{{item.tank}}</th>
        <td>{{item.temperature}}</td>
        <td>{{item.density}}</td>
        <td>{{item.data_meas|date:"d-m H:m"}}</td>
        <td>{{item.pressure}}</td>
        <td>{{item.comment}}</td>
    </tr>
    </tbody>

    {% endfor %}
</table>
{% endblock %}

brewery/templates/brewery/tank_detail.html
{% extends 'base.html' %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">t°C</th>
        <th scope="col">p°</th>
        <th scope="col">Date</th>
        <th scope="col">P</th>
        <th scope="col">Comment</th>
    </tr>
    </thead>
    {% for item in brewery.measuring_set.all %}
    <tbody>
    <tr>
        <th scope="row">{{item.tank}}</th>
        <td>{{item.temperature}}</td>
        <td>{{item.density}}</td>
        <td>{{item.data_meas|date:"d-m H:m"}}</td>
        <td>{{item.pressure}}</td>
        <td>{{item.comment}}</td>
    </tr>
    </tbody>
    {% endfor %}
</table>
<a href="{% url 'delete_tank' brewery.pk %} " class="btn btn-danger" style="float: right;">Delete</a>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Tanks{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
{% include 'inc/_nav.html' %}
<div class="container m-3">
    <div class="row">
        <div class="col-md-3">
            {% block sidebar %}
            {% endblock %}
        </div>
        <div class="col-md-9">
        {% block content %}
        {% endblock %}
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
</html>

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Home page</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'add_measuring' %}">Add measuring</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_tank' %}">Add Tank</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tanks Control
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Add Tank</a></li>
            <li><a class="dropdown-item" href="#">Delete Tank</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Link</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/inc/_sidebar.html
{% load brew_tags %}
<div class="list-group">
    <a class="list-group-item list-group-item-action active">Tanks Full:</a>
    {% get_tanks as tanks %}
    {% for item in tanks %}
    <a href="{% url 'tanks' item.pk %}" class="list-group-item list-group-item-action active">
        # {{ item.number }} - {{item.title}}</a>
    {% endfor %}
</div>